[project]
name = "okx-agent"
version = "0.1.0"
description = "OKX Crypto Price Analysis Agent using AgentScope and MCP"
authors = [
    { name = "LFlops", email = "glide_nether0x@icloud.com" },
]
requires-python = ">=3.12"
dependencies = [
    "agentscope>=1.0.3",
    "ccxt>=4.5.5",
]

[project.scripts]
okx-server = "okx_mcp_server:main"
okx-agent = "main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# 明确告诉 setuptools 在 src 目录下查找包
package-dir = {"" = "src"}
# 明确告诉 setuptools 不要在顶层查找任何模块，只找包
py-modules = []
packages = [""]